name: Print Hello World
on: 
    push :
jobs:
    print:
        runs-on: macOS-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - name: Run test
              run: npm ci
            - name: Run test
              run: npm test

            
 